---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  labels:
    app: diplom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
        - name: testapp
          image: uppeator/diplom:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1"
